### PR TITLE
React Native parity

### LINKED ISSUE #42: Error while installing via npm
Screenshot 2024-05-21 at 1 00 53 PM

I'm guessing it's because the [`peerDependency`](https://github.com/nanostores/query/blob/main/package.json#L64) mentioned is incorrect.
Shouldn't it be `>=0.10` ?

### LINKED ISSUE #44: Can't install @nanostores/query (npm ERR! code ERESOLVE)
Hi!

I just updated `nanostores` and `@nanostores/query` in a project, but got npm errors.
So I tested to install these two packages in a new and empty project and got the same errors...

First I installed `nanostores`:
```sh
➜  npm i nanostores

added 1 package, and audited 2 packages in 2s
```

That works, but when I install `@nanostores/query` I get an ERESOLVE error:
```sh
➜  npm i @nanostores/query
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: nanostores@0.10.3
npm ERR! node_modules/nanostores
npm ERR!   nanostores@"^0.10.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer nanostores@">0.10" from @nanostores/query@0.3.0
npm ERR! node_modules/@nanostores/query
npm ERR!   @nanostores/query@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I use node v20.11.1 (npm v10.2.4).
If I try installing an older version of `@nanostores/query` (`npm i @nanostores/query@0.2.10`) everything works fine.

Is this some problem with `@nanostores/query` or is it my machine?

### PR DESCRIPTION
**Pull request by dkzlv**
Actually Fixes #42, Fixes #44.

### CODE REVIEW

**Comment by dkzlv** [comment]
@hemandev Would you mind taking a look and possibly even testing it? I'm not really an expert in RN at all, and currently, I think, you're the only RN user we have 😅

I published a beta for this library with a transparent support for RN.
You can install it like this: `npm install @nanostores/query@beta`.

**Comment by hemandev** [comment]
IMG_0475

I am getting the same error. I'm guessing its because its still trying to use `nanoquery.umd.cjs` instead of the `nanoquery.native.cjs`. I will have to look more into this.

The `react-native` exports is relatively new isn't it? Do you know if `metro` bundler supports it by default?

**Comment by dkzlv** [comment]
@hemandev Oooh, I see. It's been there [for a year already](https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta), but it's considered experimental/unstable.

Try again, please! Now you'll need to import like this:

```ts
import { nanoquery } from "@nanostores/query/react-native";
```

**Comment by dkzlv** [comment]
@hemandev Merging for now, lmk if it doesn't work for you.

**Comment by sitarass** [comment]
@dkzlv still not working
image

**Comment by ice-cap0** [comment]
yeah same

**Comment by ice-cap0** [comment]
extensive react-native user here 
happy to test !

**Pull request merged**
